### ISSUE TITLE
JPSPlus Exception

### ISSUE THREAD

**Issue by xKaddo** [OpenNos/OpenNos#1640]
http://pastebin.com/2wHiX57L

**Comment by 0Lucifer0** [comment]
fixed

**Comment by xKaddo** [comment]
http://pastebin.com/B4dgYEUZ
not really ;o

**Comment by Uppermost** [comment]
Always not fixed, cause world server crash

**Comment by 0Lucifer0** [comment]
not possible there is nothing line 310.

**Comment by Uppermost** [comment]
00:35 Not fixed

System.NullReferenceException: Object reference not set to an instance of an object.
   at EpPathFinding.JumpPointFinder.FindPath(JumpPointParam iParam) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.EpPathFinding\PathFinder\JumpPointFinder.cs:line 311
   at OpenNos.GameObject.Map.JPSPlus(JumpPointParam JumpPointParameters, GridPos cell1, GridPos cell2) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.GameObject\Map\Map.cs:line 308
   at OpenNos.GameObject.MapMonster.FollowTarget(ClientSession targetSession) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.GameObject\Map\MapMonster.cs:line 764
2016-12-01 00:33:09,384 [17] ERROR OpenNos.World.Program [(null)] - Pathfinding using JPSPlus failed. Map: 236 StartX: 151 StartY: 201 TargetX: 143 TargetY: 209
System.NullReferenceException: Object reference not set to an instance of an object.
   at EpPathFinding.JumpPointFinder.FindPath(JumpPointParam iParam) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.EpPathFinding\PathFinder\JumpPointFinder.cs:line 311
   at OpenNos.GameObject.Map.JPSPlus(JumpPointParam JumpPointParameters, GridPos cell1, GridPos cell2) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.GameObject\Map\Map.cs:line 308
   at OpenNos.GameObject.MapMonster.FollowTarget(ClientSession targetSession) in C:\Users\Kaddo\Source\Repos\OpenNos\OpenNos.GameObject\Map\MapMonster.cs:line 764
2016-12-01 00:33:09,450 [11] INFO  OpenNos.World.Program [(null)] - Ein neuer Client hat sich verbunden. ClientId =15
2016-12-01 00:33:09,466 [17] DEBUG OpenNos.World.Program [(null)] - Client arrived, SessionId: 10
2016-12-01 00:33:10,153 [26] INFO  OpenNos.World.Program [(null)] - Account mit SessionId 12 verbunden.
2016-12-01 00:33:10,309 [30] ERROR OpenNos.World.Program [(null)] - Pathfinding using JPSPlus failed. Map: 236 StartX: 151 StartY: 202 TargetX: 142 TargetY: 209

**Comment by Uppermost** [comment]
New exception 
![image](https://cloud.githubusercontent.com/assets/15254478/20795599/46defda6-b7d2-11e6-851e-d46da7b30b81.png)
